/* Original code Copyright (c) 2013 ftvs[1]

   Original code posted here[2].

   This comment generated by code-cite[3].

   [1]: https://github.com/ftvs
   [2]: https://gist.github.com/ftvs/5822103
   [3]: https://github.com/shanecelis/code-cite
*/

using UnityEngine;
using System.Collections;

namespace SeawispHunter.MinibufferConsole {

public class CameraShake : MonoBehaviour {
  // Transform of the camera to shake. Grabs the gameObject's transform
  // if null.
  public Transform camTransform;

  // How long the object should shake for.
  public float shakeDuration = 0f;

  // Amplitude of the shake. A larger value shakes the camera harder.
  public float shakeAmount = 0.7f;
  public float decreaseFactor = 1.0f;

  Vector3 originalPos;

  void Awake() {
    if (camTransform == null)
      camTransform = GetComponent<Transform>();
  }

  void OnEnable() {
    originalPos = camTransform.localPosition;
  }

  void Update() {
    if (camTransform == null)
      return;
    if (shakeDuration > 0) {
      camTransform
        .localPosition = originalPos + Random.insideUnitSphere * shakeAmount;

      shakeDuration -= Time.deltaTime * decreaseFactor;
    } else {
      shakeDuration = 0f;
      camTransform.localPosition = originalPos;
    }
  }
}

}
