/* Original code Copyright (c) 2015 SnapStreamJason[1]
   Modified code Copyright (c) 2016 Shane Celis[2]
   Licensed under the Apache License v2.0[3]

   Original code posted here[4].

   This comment generated by code-cite[5].

   NOTE: Added authorization code and fixed to work with Unity.

   [1]: https://github.com/SnapStreamJason
   [2]: http://twitter.com/shanecelis
   [3]: https://www.apache.org/licenses/LICENSE-2.0
   [4]: https://github.com/SnapStreamJason/TinyTwitter
   [5]: https://github.com/shanecelis/code-cite
*/
using System;
using System.IO;
using System.Linq;
using System.Threading;
using System.Xml.Serialization;
using NUnit.Framework;

namespace Tiny.Twitter
{
//  [TestClass]
  public class TinyTwitterTests
  {
    private static OAuthInfo GetOAuthInfo()
    {
      var tokensFile = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "test-oauth-info.xml");

      if (!File.Exists(tokensFile))
        Assert.Fail("Cannot find oauth parameter file. Add a file named test-oauth-info.xml to the project with your own OAuth tokens. You can find a sample in sample.test-oauth-info.xml");

      var serializer = new XmlSerializer(typeof(OAuthInfo));
      using (var stream = File.OpenRead(tokensFile))
        return (OAuthInfo)serializer.Deserialize(stream);
    }

    private static TinyTwitter CreateTinyTwitter()
    {
      var oauth = GetOAuthInfo();

      var twitter = new TinyTwitter(oauth);
      return twitter;
    }

    [Test]
    public void Write_tweets_and_read_timeline()
    {
      var twitter = CreateTinyTwitter();

      var status = Guid.NewGuid().ToString();
      twitter.UpdateStatus(status);

      // Wait a little to let twitter update timelines
      Thread.Sleep(TimeSpan.FromSeconds(3));

      var tweets = twitter.GetHomeTimeline();
      Assert.AreEqual(status, tweets.First().text);
    }

    [Test]
    public void Write_many_tweets()
    {
      // Just to show the problem with HttpWebRequests and TimeoutExceptions

      var twitter = CreateTinyTwitter();

      for (var i = 0; i < 5; i++)
      {
        twitter.UpdateStatus(Guid.NewGuid().ToString());
        Thread.Sleep(TimeSpan.FromMinutes(1));
      }
    }

    [Test]
    public void Tweet_video() {

      var twitter = CreateTinyTwitter();
      var sampleFile = Path.Combine( AppDomain.CurrentDomain.BaseDirectory, "test.mp4" );

      for( var i = 0; i < 5; i++ ) {
        string media_id = null;
        using( var stream = File.OpenRead( sampleFile ) ) {
          media_id = twitter.UploadMedia( stream, "video/mp4" );
        }

        twitter.UpdateStatusWithMedia( Guid.NewGuid().ToString(), media_id );
        Assert.IsNotNull( media_id );
      }
    }
  }
}
